image: node:14-alpine

include:
  - template: Terraform.gitlab-ci.yml

variables:
  # If not using GitLab's HTTP backend, remove this line and specify TF_HTTP_* variables
  TF_STATE_NAME: default
  TF_CACHE_KEY: default
  # If your terraform files are in a subdirectory, set TF_ROOT accordingly
  # TF_ROOT: terraform/production
  
before_script:
  - export GOOGLE_CREDENTIALS=$(echo $BASE64_GOOGLE_CREDENTIALS | base64 -d)

stages:
  - init
  - validate
  - build
  - test
  - deploy
  - cleanup

install-dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    expire_in: 1hr
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

# Trabajo para construir la aplicación.
build-app:
  stage: build
  needs:
    - install-dependencies
  script:
    - npm run build

run-app:
  stage: test
  needs:
    - build-app
  script:
    - npm run start

destroy:
  extends: .terraform:destroy
  needs: []