include:
  - template: Terraform.gitlab-ci.yml

variables:
  # If not using GitLab's HTTP backend, remove this line and specify TF_HTTP_* variables
  TF_STATE_NAME: default
  TF_CACHE_KEY: default
  # If your terraform files are in a subdirectory, set TF_ROOT accordingly
  # TF_ROOT: terraform/production
  
before_script:
  - export GOOGLE_CREDENTIALS=$(echo $BASE64_GOOGLE_CREDENTIALS | base64 -d)

stages:
  - init
  - validate
  - build
  - test
  - deploy
  - cleanup

# Trabajo para construir la aplicación.
build-app:
  stage: build
  image: node:latest
  script:
    - npm run build
    - npm run start

destroy:
  extends: .terraform:destroy
  needs: []