include:
  - project: 'gitops-demo/infra/templates'
    file: '/terraform.gitlab-ci.yml'
    ref: use-gitlab-secrets

.secrets:
  secrets:
    GOOGLE_CREDENTIALS_FILE:
      vault: infrastructure/gcp/GOOGLE_CREDENTIALS@secret
    GOOGLE_PROJECT_FILE:
      vault: infrastructure/gcp/GOOGLE_PROJECT@secret
    GOOGLE_REGION_FILE:
      vault: infrastructure/gcp/GOOGLE_REGION@secret
    GITLAB_TOKEN_FILE:
      vault: infrastructure/gitlab/GITLAB_TOKEN@secret



