apiVersion: v1
kind: ConfigMap
metadata:
  name: hybrid-api-config
  labels:
    app: hybrid-auth-service
data:
  NODE_ENV: "production"
  PORT: "3001"
  DB_HOST: "mysql-afa863df-o282bbc28.database.cloud.ovh.net"
  DB_PORT: "20184"
  DB_DATABASE: "IV_HYBRID"
  DB_SSL: "true"
  DB_SSL_CA: "/app/ca.pem"