apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-auth-service
  labels:
    app: hybrid-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hybrid-auth-service
  template:
    metadata:
      labels:
        app: hybrid-auth-service
    spec:
      containers:
        - name: hybrid-auth-service
          image: 286325yk.c1.bhs5.container-registry.ovh.net/hybrid/hybrid-api-ts:1.3.5
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: hybrid-api-config
            - secretRef:
                name: hybrid-api-secret
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
      imagePullSecrets:
       - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: hybrid-auth-service
spec:
  type: ClusterIP
  selector:
    app: hybrid-auth-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001