apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-api-ts
  labels:
    app: hybrid-api-ts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hybrid-api-ts
  template:
    metadata:
      labels:
        app: hybrid-api-ts
    spec:
      containers:
        - name: hybrid-api-ts
          image: 286325yk.c1.bhs5.container-registry.ovh.net/hybrid/hybrid-api-ts:1.3.5
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: hybrid-api-config
            - secretRef:
                name: hybrid-api-secret
      imagePullSecrets:
       - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: hybrid-api-ts
spec:
  type: LoadBalancer
  selector:
    app: hybrid-api-ts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002