apiVersion: v1
kind: Secret
metadata:
  name: hybrid-api-secret
  labels:
    app: hybrid-auth-service
type: Opaque
data:
  JWT_ACCESS_TOKEN: and0SHlicmlkQXBpMjAyNQ==
  JWT_SECRET: c3VwZXJzZWNyZXRrZXkK